apiVersion: v1
kind: Pod
metadata:
  labels:
    run: licao_de_casa
  name: licao
spec:
  containers:
    - image: nginx
      name: webserver
      volumeMounts:
      - mountPath: /licao-day2
        name: licao-day2
      resources:
        limits:
          cpu: "1.8"
          memory: "256Mi"
        requests:
          cpu: "1.3"
          memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: licao-day2
    emptyDir:
      sizeLimit: 512Mi
status: {}
