apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
    - image: ubuntu
      name: ubuntu
      resources: 
        limits:
          
        requests:
          cpu: "0.3"
      args: 
      - sleep
      - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
