apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
    - image: nginx
      name: webserver
      volumeMounts:
      - mountPath: /giropops
        name: primeiro-emptydir
      resources: 
        limits:
          cpu: "1.8"
          memory: "256Mi"
        requests:
          cpu: "1.3"
          memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: primeiro-emptydir
    emptyDir: 
      sizeLimit: 256Mi
status: {}
