apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.14.0
        name: nginx
        resources:
          limits:
            cpu: 1.5
            memory: 256Mi
          requests:
            cpu: 1.0
            memory: 64Mi
